### ISSUE TITLE
Missing direction type RFC_CHANGING

### ISSUE THREAD

**Issue by tigerduck42** [php-sap/saprfc-kralik#10]
Found an issue with missing implemention of direction type **RFC_CHANGING**

https://github.com/php-sap/saprfc-kralik/blob/46b785bf6f4220106f09908eedd814da2bb9ed74/src/Traits/ApiTrait.php#L103-L107

throws 
```php
phpsap\exceptions\SapLogicException: Unknown SAP Netweaver RFC direction 'RFC_CHANGING'!
```
 https://github.com/php-sap/saprfc-kralik/blob/46b785bf6f4220106f09908eedd814da2bb9ed74/src/Traits/ApiTrait.php#L109      

![SAP](https://user-images.githubusercontent.com/3737924/149961346-1c894ad9-1e7a-467d-b1ec-43ba0fc0ba68.PNG)

**Comment by gregor-j** [comment]
[php-sap/interfaced issue 13](https://github.com/php-sap/interfaces/issues/13)

**Comment by gregor-j** [comment]
[php-sap/common issue 18](https://github.com/php-sap/common/issues/18)
